# Generated by Django 3.2.13 on 2023-02-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelo', '0002_auto_20220823_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(default='', upload_to='pics')),
                ('des', models.TextField()),
            ],
        ),
    ]
